### ISSUE TITLE
questions about clustering another dataset 

### ISSUE THREAD

**Issue by cyan07** [herandy/DEPICT#3]
Hello! I attempted to run your code on another dataset, but I'm not sure how to adapt the parameters for the new dataset.  Could you please tell me how to configure your code and which parameters to change? Thank you!

**Comment by herandy** [comment]
Generally, you should set the sizes so that the output size for the encoder would be as close to 10x10 as possible, this is mentioned in "Implementation Details" under our Experiments section:

"For  all  datasets,  we  consider two convolutional layers followed by a fully connected layer in encoder and decoder pathways. While for all convolutional layers, the feature map size is 50 and the kernel
size is about 5×5, the dimension of the embedding subspace is set equal to the number of clusters in each dataset. the dimension of the embedding subspace is set equal to the number of clusters in each dataset. We also pick the proper stride,  padding and crop to have an  output  size  of  about 10x10 in  the second  convolutional layer."

Hope this would work for your dataset as well. If there is any other question please let me know :)
